name: Pull Request

on:
  push:
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4

      - name: Enable KVM on the Github Actions runner
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Build snap
        uses: snapcrafters/ci/test-snap-build@main
        with:
          install: true

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1

      - name: Test ghvmctl
        run: |
          set -xe
          sudo snap connect ghvmctl:lxd lxd:lxd

          ghvmctl && exit 1 || true

          ghvmctl prepare

          ghvmctl run-snap it-does-not-exists.hopefully && exit 1 || true

          ghvmctl install-snap signal-desktop --channel candidate
          ghvmctl install-snap terraform --revision 584
          ghvmctl install-snap kubectl

          ghvmctl run-snap signal-desktop
          sleep 2
          ghvmctl screenshot-full
          ghvmctl screenshot-window
          ls -lht "$HOME"/ghvmctl-screenshots
          ghvmctl exec "cat /home/ubuntu/signal-desktop.log"

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ~/ghvmctl-screenshots
          if-no-files-found: error
